# Generated by Django 5.2.13 on 2026-04-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examiner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PublicExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=30)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('exam_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examiner.examiner')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_exam.candidate')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_exam.publicexam')),
            ],
            options={
                'unique_together': {('exam', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='PublicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=20)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_exam.publicexam')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=20, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_exam.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_exam.publicquestion')),
            ],
        ),
    ]
