# Generated by Django 5.2.13 on 2026-04-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_exam', '0002_publicexam_created_at_publicexam_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicexam',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicexam',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
