# Generated by Django 5.2.13 on 2026-04-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_exam', '0003_publicexam_total_questions_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='publicexam',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='entered_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='entered_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='entered_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
